apiVersion: v1
kind: Service
metadata: 
      name: clusterservice
      labls: 
        app: clusterservice 
spec:
  type: ClusterIp
  selector:
    app: example-app 
  ports:
    - port: 80
      #targetPort: 80
      name: nginx
      protocol: TCP
